### PR TITLE
Updated login flow to match Figma (#1167, #1128)

### PR DESCRIPTION
**Pull request by daveoconnor**
Includes email for various signup/login related events which we'll need to ensure there's support for in staging and prod

### CODE REVIEW

**Comment by daveoconnor** [comment]
It does block, and the figma doc states "Sign up via email would go through a confirmation process that would require clicking a link in a received email",

**Review by rbbeeston — APPROVED** [review]
LGTM!

**Comment by sdarwin** [comment]
Hi @daveoconnor , I noticed the admin user account on boost.io was prompted to validate email recently.   Probably it's from this pull request:  "Sign up via email would go through a confirmation process".    

Maybe there is no issue, but to investigate - what occurs on a new installation of the codebase?

1. You install website-v2 in a fresh installation.  
2. It requests to validate the initial admin user ?
3. Since email might not be functioning yet, there is no way to validate the email.
4. You are blocked from logging in as the admin user and locked out of the installation?   or not.

searching docs/ for "validate" or "confirm" doesn't have a result.  

what happens in this case? just to understand.
thanks.

**Comment by daveoconnor** [comment]
Hi Sam,
Generally the method to create an admin user would be to run `python manage.py createsuperuser` on the server, and for that there's no validation, the user is considered a safe one because it's run on the server. I'm not seeing anywhere that that gets called though, e.g. in the github actions, so I'm not sure how these are being set up.

The verification email is only sent when working through the main website allauth signup/login pages. 

What I think probably happened is, if the admin user then tried to log in to the normal login page rather than the admin login page, they may well have been sent a verification email at that point. Does that seem plausible to you based on what you're seeing for the user's email address?

**Comment by sdarwin** [comment]
>  if the admin user then tried to log in to the normal login page rather than the admin login page, they may well have been sent a verification email at that point.

Yes that is what I was seeing. If the admin user tries to log in, there is a request for verification. Otherwise the login doesn't proceed.     
That means if email connectivity hasn't been configured the admin can never log in, at the beginning.  
But your solution fixes it.    
The work-around is to login directly on the /admin/ page which is different from the website signup/login pages.    
Therefore, since that option exists, it should be ok.   Thanks for the explanation.

**Pull request merged**
