### PR TITLE
736 hyperkitty

### PR DESCRIPTION
**Pull request by frankwiles**
This PR has two migrations that **WILL FAIL** for you both locally and in deployed environments.  To work around this [this bug](https://gitlab.com/mailman/hyperkitty/-/issues/486) in hyperkitty you must execute the following: 

`manage.py migrate`

It will fail on Hyperkitty's 7th migration 

`manage.py migrate --fake hyperkitty 0007_allauth_20160808_1604`

Run migrate again to run the 8th migration, it will fail on the 9th one

`manage.py migrate`

Fake the 9th migration with: 

`manage.py migrate --fake hyperkitty 0009_duplicate_persona_users`

And finally run the rest of the migrations successfully: 

`manage.py migrate`

@sdarwin I don't have access to your clusters, so I can't just take care of this.  I would suggest you merge this when you're ready and do the following against your database(s).

### CODE REVIEW

**Comment by sdarwin** [comment]
@frankwiles , could we

 -  Fork Hyperkitty from gitlab. Clone into https://github.com/cppalliance/hyperkitty.   From this commit 2fa149e6 · Merge branch 'deps' into 'master' · 5 days ago  Release: v1.3.8.   

  - In requirements.txt, install from the cppalliance repo (instead of the normal pip package)
 - Fix the migrations .  Hopefully in some backwards-compatible and correct way.
 - Send the changes upstream back to gitlab.
 
With this method all our many environments, including dev, prod, docker-compose, won't fail when installing.

**Comment by sdarwin** [comment]
- Created https://github.com/cppalliance/hyperkitty
- Set default branch to 'boost', where we could add customizations
- Added members

How can that be included in temp-site.  requirements.txt:

HyperKitty @ git+https://github.com/cppalliance/hyperkitty@2fa149e
or 
HyperKitty @ git+https://github.com/cppalliance/hyperkitty@boost

Eventually specifying a static tag such as @2fa149e is more stable. In the short term @boost would track the branch and be updated quickly.

What about requirements.in.

Pip packages installed in a mailman3-test environment:

HyperKitty            1.3.7
mailman               3.3.8
mailman-hyperkitty    1.2.1
mailman-web           0.0.6
mailmanclient         3.3.5
postorius             1.3.8

consider the purpose of each.

**Comment by frankwiles** [comment]
@sdarwin my concern would be if they were not receptive to the changes we might have to keep up the fork on our own.

**Comment by frankwiles** [comment]
Fork work is tracked in #759 

@sdarwin I'm also going to need a django_mailman3 repo for https://gitlab.com/mailman/django-mailman3/-/issues/69

**Comment by sdarwin** [comment]
- New repo https://github.com/cppalliance/django-mailman3   . Also a default branch 'boost' for customizations.

- "my concern would be if they were not receptive".  Anything is possible.  I believe they have advertised mailman3 as a modular system that can be integrated in a Django project, and so ought to be willing to accept improvements towards that. 

- We might have to sell them on the features. "This is very convenient!!  It allows anyone to embed Hyperkitty in their website."     And if work is already done, all they have to do is click the "Merge" button.

**Comment by frankwiles** [comment]
Closing this as it's old and we're headed down an entirely different path now.

**Pull request closed without merging**
