### PR TITLE
Allow users to Deactivate

### PR DESCRIPTION
**Pull request by kennethreitz**
This pull request addresses #965. It allows users to deactivate their accounts. 

In addition, a new "Your account is deactivated" page is present if they try to log in with their account again. This is useful in the case of us deactivating a user for unwanted access.

### CODE REVIEW

**Comment by vinniefalco** [comment]
Is this going to be squashed?

**Comment by kennethreitz** [comment]
yes, all PRs are squashed into a single commit now

**Comment by kennethreitz** [comment]
I should say, it's the default merge behavior :)

**Comment by kennethreitz** [comment]
@rbbeeston can you take a look at updating the template for `profile.html`? We probably need some frontend "are you sure?" validation there too (ref: https://github.com/boostorg/website-v2/pull/1170/files#diff-40f7faefd30d053f0caedcda1146bde4b07f6b64e61036f3635505b99872c036)

**Comment by vinniefalco** [comment]
> it's the default merge behavior :)

Are you using the web interface to merge PRs? Is the merge behavior configured in the repo settings?

**Pull request closed without merging**
