### PR TITLE
Fix for styles on dark mode checkbox and final placeholder fix

### LINKED ISSUE #770: Profile edit - Checkbox styling in dark mode
In light mode, a checkbox retains its shape when checked.  In dark mode, it changes from checkbox to check.  Should also be a box.

image

image

### LINKED ISSUE #810: Library detail - Lozenge difference between browsers
Top of lozenge on library detail getting cut off.

In FF (possibly others):
image

vs Chrome:
image

### LINKED ISSUE #811: Learn Page - rounded corners update
Make all corners rounded on the outer panels.

### PR DESCRIPTION
**Pull request by 4down**
- resolves #770
- resolves #810
- resolves #811
- removes the hover state in light mode on the homepage button that had been replicated from the login button (will deal with later)
- addresses the rounded corners on the leanr 
- fully resolves placeholder text issue (profile edit)
- also adjusts dropdown to make them the same size on releases and libraries by setting a minimum width

### CODE REVIEW

**Comment by kennethreitz** [comment]
I was hoping that would re-trigger a CI run.

**Comment by sdarwin** [comment]
> I was hoping that would re-trigger a CI run.

There are conflicting files.  Spencer could resolve the conflicts and/or push a small update to the pull request.

**Comment by vinniefalco** [comment]
3-month old PR?

**Comment by 4down** [comment]
This was a PR that couldn't be merged at the time due to an issue from a merge that had gone in prior that had to be resolved before I would have been able to merge this.  I kept doing additional work while waiting, and rolled it all into a PR that included the fixes that held this up, so there's nothing in this PR that didn't already make it in.  Sorry, I should have closed it when I did the follow-up - I didn't realize it was still here.  Leaving open for the moment because I need to see what if anything might have happened above.  But, there should be no reason to merge this and all referenced issues in the initial comment were mentioned again - #824

**Comment by kennethreitz** [comment]
Thank you @4down!

**Pull request closed without merging**
