### PR TITLE
Update styling in release report

### LINKED ISSUE #1527: rework styling of release report
Work with Rob on cleaning up the styling for the release report.

### PR DESCRIPTION
**Pull request by brianjp93**
- fixes #1527

### CODE REVIEW

**Comment by brianjp93** [comment]
image
image
image
image
image

**Comment by rbbeeston** [comment]
Let's make the logo a bit bigger so it matches the text height

**Comment by vinniefalco** [comment]
If we are going to put the logo on every subsequent page lets not also put the word Boost next to it

**Comment by vinniefalco** [comment]
Anyway this should be merged right away since it is an improvement. And we should keep refining.

**Comment by brianjp93** [comment]
[Boost.pdf](https://github.com/user-attachments/files/18067885/Boost.pdf)

**Comment by rbbeeston** [comment]
Jumping on Vinnie's slack comment, the avatars with the values under the names should be consistent and not use parentheses around the numbers, and give context next to them, as "235 Messages" or "12 commits"

**Review by rbbeeston — APPROVED** [review]
Good with the latest changes, ok to merge

**Pull request merged**
