### PR TITLE
Show asciidocs library docs in iframe

### PR DESCRIPTION
**Pull request by daveoconnor**
Related to ticket #1358, libraries docs iframe

~~This also contains some of the work for refactoring away from version selects being copy pasted everywhere.~~ Removed for now, had side effects.

### CODE REVIEW

**Comment by vinniefalco** [comment]
1. This applies to all libraries not just those rendered with asciidoctor?
2. What is the mechanism to determine whether or not the header is injected in an iframe, versus integrated into the page?
3.

**Comment by daveoconnor** [comment]
> 1. This applies to all libraries not just those rendered with asciidoctor?

It will apply to all libraries which aren't Antora docs.

> 2. What is the mechanism to determine whether or not the header is injected in an iframe, versus integrated into the page?

There was no indicator in the content type what the source was, the content was already converted to html when it was put onto s3 from where we retrieve it, so after discussing with Rob we settled on using a lack of a "spirit-nav" in the content to flag it as an ascii doc. (not strictly true but fine for our uses here).

This has the added bonus of putting documentation that's html-based (e.g. in the Assign library) in the iframe too.

**Review by rbbeeston — APPROVED** [review]
In your test, it also has a logo with a relative path. Does that actually work?

LGTM!

**Comment by daveoconnor** [comment]
> In your test, it also has a logo with a relative path. Does that actually work?
> 
> LGTM!

It does! See bottom right icon. (The positioning is from their css)

relativeicon

**Pull request merged**
