### PR TITLE
Add license header to all source files

### PR DESCRIPTION
**Pull request by ashtum**

### CODE REVIEW

**Comment by sdarwin** [comment]
This pull request generally looks fine.  @ashtum out of curiosity, did you write a script or find an existing one online?

@frankwiles can this be merged?

**Comment by ashtum** [comment]
> This pull request generally looks fine. @ashtum out of curiosity, did you write a script or find an existing one online?
> 
> @frankwiles can this be merged?

I used https://github.com/johann-petrak/licenseheaders with [a little bit of modification](https://github.com/ashtum/licenseheaders/commit/4a6a88673d5fc17506c260c09ca7f5c04660f126) to suite our needs.

**Comment by frankwiles** [comment]
This isn't necessary to license software (in terms of a legal requirement) and is just noise in every file.  I'd rather we not merge this.

**Comment by frankwiles** [comment]
I see in Slack, however, that @vinniefalco is requesting it.  This is likely going to break some things FYI as it's going to put comments in incorrectly and/or in places that aren't expecting them.  In markdown, Helm chart yaml, etc. are the places I'm guessing we'll see some fall out from this.

**Comment by glenfe** [comment]
W can relax it. It doesn't have to be 100% of files, best effort is fine.

**Comment by sdarwin** [comment]
> best effort is fine

In that case, please exclude the entire kube/ directory (at least).    
Other files might be excluded also. 
There are pull request branch conflicts, need to rebase from develop.

**Comment by vinniefalco** [comment]
Lets put this PR on pause and instead submit a series of smaller uncontroversial PRs that update subsets of files which are known not to break anything. I will transfer the repo now, as the entire thing is BSL licensed already due to the project setting and the license file in the root.

**Comment by kennethreitz** [comment]
Closing for now, we can re-open if needed.

**Comment by vinniefalco** [comment]
I'm all for marking more files individually as BSL licensed, but there is no rush to do so, and I don't know what all the rules are for each language/script type.

**Pull request closed without merging**
